# Release: https://github.com/QSTN-US/qstn-v2-secretvm/releases/tag/v1.1.3
# Workflow URL: https://github.com/QSTN-US/qstn-v2-secretvm/actions/runs/24172686229
# Commit: https://github.com/QSTN-US/qstn-v2-secretvm/commit/67768dec45b4175bbd386cf9a6ac86c2df8e925b
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/qstn-us/qstn-v2-secretvm@sha256:8dda25547776f5bd4c68739c48588191d6f2b0112182b8450ab72973b68b0b4f
    ports:
      - '3000'
