# Release: https://github.com/QSTN-US/qstn-v2-secretvm/releases/tag/v1.0.0
# Workflow URL: https://github.com/QSTN-US/qstn-v2-secretvm/actions/runs/23372958372
# Commit: https://github.com/QSTN-US/qstn-v2-secretvm/commit/35c0c02f4b1e95ff6d740cb90ea0c8f800f6c36b
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/qstn-us/qstn-v2-secretvm@sha256:972bbd5c25b0a05bf6aa2a923ec3dacfe9453d63baebfcc10c9fcce78292e22e
    ports:
      - '3000'
